# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Pollen - Windows

on:
  push:
    tags:
      - v.**
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src
    - uses: actions/upload-artifact@v3
      with:
        name: Pollen_windows
        path: src/dist/windows
    - uses: actions/upload-artifact@v3
      with:
        name: Pollen_windows
        path: configuration.json
    - uses: actions/upload-artifact@v3
      with:
        name: Pollen_windows
        path: LEGGIMI.txt
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: true
        prerelease: false
        release_name: ${{ github.ref }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
